const fs = require('fs');
const path = require('path');

// 1. First extract existing 213 verified stocks from stockResolver.ts
const stockResolverPath = path.resolve(__dirname, '../server/utils/stockResolver.ts');
const content = fs.readFileSync(stockResolverPath, 'utf8');

const regex = /\{\s*symbol:\s*\"([^\"]+)\",\s*scripCode:\s*\"([^\"]+)\",\s*name:\s*\"([^\"]+)\"(?:,\s*nameKeywords:[^}]+)?(?:,\s*sector:\s*\"([^\"]+)\")?\s*\}/g;
let m;
const masterMap = new Map();

while ((m = regex.exec(content)) !== null) {
  const symbol = m[1].toUpperCase().trim();
  const scripCode = m[2].trim();
  const name = m[3].trim();
  const sector = m[4] || 'Equities';
  if (!masterMap.has(symbol)) {
    masterMap.set(symbol, {
      symbol,
      name,
      scripCode,
      industry: sector
    });
  }
}

// 2. Comprehensive supplementary Nifty 500 constituents with official BSE scrip codes
const additionalNifty500 = [
  { symbol: "3MINDIA", name: "3M India Ltd", scripCode: "523395", industry: "Diversified" },
  { symbol: "ABB", name: "ABB India Ltd", scripCode: "500002", industry: "Capital Goods" },
  { symbol: "ACC", name: "ACC Ltd", scripCode: "500410", industry: "Construction Materials" },
  { symbol: "AIAENG", name: "AIA Engineering Ltd", scripCode: "532683", industry: "Industrial Manufacturing" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Ltd", scripCode: "533758", industry: "Capital Goods" },
  { symbol: "AARTIIND", name: "Aarti Industries Ltd", scripCode: "524208", industry: "Chemicals" },
  { symbol: "AAVAS", name: "Aavas Financiers Ltd", scripCode: "541988", industry: "Financial Services" },
  { symbol: "ABBOTINDIA", name: "Abbott India Ltd", scripCode: "500488", industry: "Healthcare" },
  { symbol: "ACE", name: "Action Construction Equipment Ltd", scripCode: "532762", industry: "Capital Goods" },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions Ltd", scripCode: "539254", industry: "Power" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd", scripCode: "541450", industry: "Power" },
  { symbol: "ADANIPOWER", name: "Adani Power Ltd", scripCode: "533096", industry: "Power" },
  { symbol: "ATGL", name: "Adani Total Gas Ltd", scripCode: "542066", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "AWL", name: "Adani Wilmar Ltd", scripCode: "543458", industry: "Fast Moving Consumer Goods" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital Ltd", scripCode: "540691", industry: "Financial Services" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion and Retail Ltd", scripCode: "535755", industry: "Consumer Services" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma Ltd", scripCode: "532331", industry: "Healthcare" },
  { symbol: "APLLTD", name: "Alembic Pharmaceuticals Ltd", scripCode: "533573", industry: "Healthcare" },
  { symbol: "ALKEM", name: "Alkem Laboratories Ltd", scripCode: "539523", industry: "Healthcare" },
  { symbol: "ALOKINDS", name: "Alok Industries Ltd", scripCode: "521070", industry: "Textiles" },
  { symbol: "AMBER", name: "Amber Enterprises India Ltd", scripCode: "540902", industry: "Consumer Durables" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd", scripCode: "500425", industry: "Construction Materials" },
  { symbol: "ANGELONE", name: "Angel One Ltd", scripCode: "543235", industry: "Financial Services" },
  { symbol: "ANURAS", name: "Anupam Rasayan India Ltd", scripCode: "543275", industry: "Chemicals" },
  { symbol: "APARINDS", name: "Apar Industries Ltd", scripCode: "532259", industry: "Capital Goods" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Ltd", scripCode: "508869", industry: "Healthcare" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Ltd", scripCode: "500877", industry: "Automobile and Auto Components" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance India Ltd", scripCode: "543335", industry: "Financial Services" },
  { symbol: "ASAHIINDIA", name: "Asahi India Glass Ltd", scripCode: "515030", industry: "Automobile and Auto Components" },
  { symbol: "ASTERDM", name: "Aster DM Healthcare Ltd", scripCode: "540975", industry: "Healthcare" },
  { symbol: "ASTRAL", name: "Astral Ltd", scripCode: "532830", industry: "Building Materials" },
  { symbol: "ATUL", name: "Atul Ltd", scripCode: "500027", industry: "Chemicals" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Ltd", scripCode: "524804", industry: "Healthcare" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds Ltd", scripCode: "512573", industry: "Fast Moving Consumer Goods" },
  { symbol: "BASF", name: "BASF India Ltd", scripCode: "500042", industry: "Chemicals" },
  { symbol: "BEML", name: "BEML Ltd", scripCode: "500048", industry: "Capital Goods" },
  { symbol: "BLS", name: "BLS International Services Ltd", scripCode: "540073", industry: "Consumer Services" },
  { symbol: "BOSCHLTD", name: "Bosch Ltd", scripCode: "500530", industry: "Automobile and Auto Components" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Ltd", scripCode: "500547", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd", scripCode: "500825", industry: "Fast Moving Consumer Goods" },
  { symbol: "BATAINDIA", name: "Bata India Ltd", scripCode: "500043", industry: "Consumer Durables" },
  { symbol: "BAYERCROP", name: "Bayer CropScience Ltd", scripCode: "506285", industry: "Chemicals" },
  { symbol: "BERGEPAINT", name: "Berger Paints India Ltd", scripCode: "509480", industry: "Consumer Durables" },
  { symbol: "BHARATFORG", name: "Bharat Forge Ltd", scripCode: "500493", industry: "Automobile and Auto Components" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd", scripCode: "500103", industry: "Capital Goods" },
  { symbol: "BIOCON", name: "Biocon Ltd", scripCode: "532523", industry: "Healthcare" },
  { symbol: "BIRLACORPN", name: "Birla Corporation Ltd", scripCode: "500335", industry: "Construction Materials" },
  { symbol: "BSOFT", name: "Birlasoft Ltd", scripCode: "532400", industry: "Information Technology" },
  { symbol: "BLSTARCO", name: "Blue Star Ltd", scripCode: "500067", industry: "Consumer Durables" },
  { symbol: "CANBK", name: "Canara Bank", scripCode: "532483", industry: "Financial Services" },
  { symbol: "CANFINHOME", name: "Can Fin Homes Ltd", scripCode: "511196", industry: "Financial Services" },
  { symbol: "CARBORUNIV", name: "Carborundum Universal Ltd", scripCode: "513373", industry: "Capital Goods" },
  { symbol: "CASTROLIND", name: "Castrol India Ltd", scripCode: "500870", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "CEATLTD", name: "CEAT Ltd", scripCode: "500878", industry: "Automobile and Auto Components" },
  { symbol: "CENTRALBK", name: "Central Bank of India", scripCode: "532885", industry: "Financial Services" },
  { symbol: "CDSL", name: "Central Depository Services (India) Ltd", scripCode: "542651", industry: "Financial Services" },
  { symbol: "CENTURYPLY", name: "Century Plyboards (India) Ltd", scripCode: "532548", industry: "Building Materials" },
  { symbol: "CENTURYTEX", name: "Century Textiles & Industries Ltd", scripCode: "500096", industry: "Textiles" },
  { symbol: "CERA", name: "Cera Sanitaryware Ltd", scripCode: "532443", industry: "Building Materials" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers and Chemicals Ltd", scripCode: "500085", industry: "Chemicals" },
  { symbol: "CHEMPLASTS", name: "Chemplast Sanmar Ltd", scripCode: "543336", industry: "Chemicals" },
  { symbol: "CHOLAHLDNG", name: "Cholamandalam Financial Holdings Ltd", scripCode: "504973", industry: "Financial Services" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment and Finance Company Ltd", scripCode: "511243", industry: "Financial Services" },
  { symbol: "CIPLA", name: "Cipla Ltd", scripCode: "500087", industry: "Healthcare" },
  { symbol: "CUB", name: "City Union Bank Ltd", scripCode: "532210", industry: "Financial Services" },
  { symbol: "CLEAN", name: "Clean Science and Technology Ltd", scripCode: "543318", industry: "Chemicals" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard Ltd", scripCode: "540679", industry: "Capital Goods" },
  { symbol: "COFORGE", name: "Coforge Ltd", scripCode: "532541", industry: "Information Technology" },
  { symbol: "COLPAL", name: "Colgate-Palmolive (India) Ltd", scripCode: "500830", industry: "Fast Moving Consumer Goods" },
  { symbol: "CAMS", name: "Computer Age Management Services Ltd", scripCode: "543232", industry: "Financial Services" },
  { symbol: "CONCOR", name: "Container Corporation of India Ltd", scripCode: "531349", industry: "Services" },
  { symbol: "COROMANDEL", name: "Coromandel International Ltd", scripCode: "506395", industry: "Chemicals" },
  { symbol: "CREDITACC", name: "CreditAccess Grameen Ltd", scripCode: "541770", industry: "Financial Services" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals Ltd", scripCode: "539876", industry: "Consumer Durables" },
  { symbol: "CUMMINSIND", name: "Cummins India Ltd", scripCode: "500480", industry: "Capital Goods" },
  { symbol: "CYIENT", name: "Cyient Ltd", scripCode: "532175", industry: "Information Technology" },
  { symbol: "DABUR", name: "Dabur India Ltd", scripCode: "500096", industry: "Fast Moving Consumer Goods" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Ltd", scripCode: "542211", industry: "Construction Materials" },
  { symbol: "DATAPATTNS", name: "Data Patterns (India) Ltd", scripCode: "543428", industry: "Capital Goods" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilisers and Petrochemicals Corp Ltd", scripCode: "501425", industry: "Chemicals" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Ltd", scripCode: "506401", industry: "Chemicals" },
  { symbol: "DELHIVERY", name: "Delhivery Ltd", scripCode: "543529", industry: "Services" },
  { symbol: "DEVYANI", name: "Devyani International Ltd", scripCode: "543330", industry: "Consumer Services" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd", scripCode: "532488", industry: "Healthcare" },
  { symbol: "DIXON", name: "Dixon Technologies (India) Ltd", scripCode: "540699", industry: "Consumer Durables" },
  { symbol: "LALPATHLAB", name: "Dr. Lal PathLabs Ltd", scripCode: "539524", industry: "Healthcare" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Ltd", scripCode: "500124", industry: "Healthcare" },
  { symbol: "EIDPARRY", name: "E.I.D. - Parry (India) Ltd", scripCode: "500125", industry: "Chemicals" },
  { symbol: "EIHOTEL", name: "EIH Ltd", scripCode: "500840", industry: "Consumer Services" },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd", scripCode: "505200", industry: "Automobile and Auto Components" },
  { symbol: "ELECON", name: "Elecon Engineering Company Ltd", scripCode: "505700", industry: "Capital Goods" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments Ltd", scripCode: "522074", industry: "Capital Goods" },
  { symbol: "EMAMILTD", name: "Emami Ltd", scripCode: "531162", industry: "Fast Moving Consumer Goods" },
  { symbol: "ENDURANCE", name: "Endurance Technologies Ltd", scripCode: "540153", industry: "Automobile and Auto Components" },
  { symbol: "ENGINERSIN", name: "Engineers India Ltd", scripCode: "532178", industry: "Construction" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank Ltd", scripCode: "543243", industry: "Financial Services" },
  { symbol: "ERIS", name: "Eris Lifesciences Ltd", scripCode: "540596", industry: "Healthcare" },
  { symbol: "ESCORTS", name: "Escorts Kubota Ltd", scripCode: "500495", industry: "Capital Goods" },
  { symbol: "EXIDEIND", name: "Exide Industries Ltd", scripCode: "500086", industry: "Automobile and Auto Components" },
  { symbol: "FDC", name: "FDC Ltd", scripCode: "531599", industry: "Healthcare" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures Ltd (Nykaa)", scripCode: "543384", industry: "Consumer Services" },
  { symbol: "FEDERALBNK", name: "Federal Bank Ltd", scripCode: "500469", industry: "Financial Services" },
  { symbol: "FACT", name: "Fertilisers and Chemicals Travancore Ltd", scripCode: "590024", industry: "Chemicals" },
  { symbol: "FINEORG", name: "Fine Organic Industries Ltd", scripCode: "541557", industry: "Chemicals" },
  { symbol: "FINCABLES", name: "Finolex Cables Ltd", scripCode: "500144", industry: "Communication" },
  { symbol: "FINPIPE", name: "Finolex Industries Ltd", scripCode: "500940", industry: "Building Materials" },
  { symbol: "FSL", name: "Firstsource Solutions Ltd", scripCode: "532809", industry: "Information Technology" },
  { symbol: "FORTIS", name: "Fortis Healthcare Ltd", scripCode: "532843", industry: "Healthcare" },
  { symbol: "GAIL", name: "GAIL (India) Ltd", scripCode: "532155", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure Ltd", scripCode: "532754", industry: "Services" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Ltd", scripCode: "532296", industry: "Healthcare" },
  { symbol: "MEDANTA", name: "Global Health Ltd (Medanta)", scripCode: "543654", industry: "Healthcare" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips India Ltd", scripCode: "500163", industry: "Fast Moving Consumer Goods" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Ltd", scripCode: "532424", industry: "Fast Moving Consumer Goods" },
  { symbol: "GODREJIND", name: "Godrej Industries Ltd", scripCode: "500164", industry: "Diversified" },
  { symbol: "GODREJPROP", name: "Godrej Properties Ltd", scripCode: "533150", industry: "Realty" },
  { symbol: "GRANULES", name: "Granules India Ltd", scripCode: "532482", industry: "Healthcare" },
  { symbol: "GRAPHITE", name: "Graphite India Ltd", scripCode: "509488", industry: "Capital Goods" },
  { symbol: "GRINDWELL", name: "Grindwell Norton Ltd", scripCode: "506076", industry: "Capital Goods" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Ltd", scripCode: "539336", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers & Chem Ltd", scripCode: "500670", industry: "Chemicals" },
  { symbol: "GSPL", name: "Gujarat State Petronet Ltd", scripCode: "532702", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "HATHWAY", name: "Hathway Cable & Datacom Ltd", scripCode: "533162", industry: "Media" },
  { symbol: "HAVELLS", name: "Havells India Ltd", scripCode: "517354", industry: "Consumer Durables" },
  { symbol: "HEG", name: "HEG Ltd", scripCode: "509631", industry: "Capital Goods" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd", scripCode: "500182", industry: "Automobile and Auto Components" },
  { symbol: "HFCL", name: "HFCL Ltd", scripCode: "500183", industry: "Telecommunication" },
  { symbol: "HIKAL", name: "Hikal Ltd", scripCode: "524735", industry: "Healthcare" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation Ltd", scripCode: "500104", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Ltd", scripCode: "500188", industry: "Metals & Mining" },
  { symbol: "HITACHI", name: "Hitachi Energy India Ltd", scripCode: "543187", industry: "Capital Goods" },
  { symbol: "HOMEFIRST", name: "Home First Finance Company India Ltd", scripCode: "543259", industry: "Financial Services" },
  { symbol: "HONAUT", name: "Honeywell Automation India Ltd", scripCode: "517174", industry: "Capital Goods" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corporation Ltd", scripCode: "540530", industry: "Financial Services" },
  { symbol: "IDBI", name: "IDBI Bank Ltd", scripCode: "500116", industry: "Financial Services" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd", scripCode: "539437", industry: "Financial Services" },
  { symbol: "IFCI", name: "IFCI Ltd", scripCode: "500106", industry: "Financial Services" },
  { symbol: "IIFL", name: "IIFL Finance Ltd", scripCode: "532636", industry: "Financial Services" },
  { symbol: "IRB", name: "IRB Infrastructure Developers Ltd", scripCode: "532947", industry: "Construction" },
  { symbol: "IRCON", name: "Ircon International Ltd", scripCode: "541956", industry: "Construction" },
  { symbol: "ITC", name: "ITC Ltd", scripCode: "500875", industry: "Fast Moving Consumer Goods" },
  { symbol: "ITI", name: "ITI Ltd", scripCode: "523610", industry: "Telecommunication" },
  { symbol: "INDIACEM", name: "India Cements Ltd", scripCode: "530005", industry: "Construction Materials" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH Ltd", scripCode: "542726", industry: "Consumer Services" },
  { symbol: "INDIANB", name: "Indian Bank", scripCode: "532814", industry: "Financial Services" },
  { symbol: "IEX", name: "Indian Energy Exchange Ltd", scripCode: "540750", industry: "Financial Services" },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd", scripCode: "530965", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "IOB", name: "Indian Overseas Bank", scripCode: "532388", industry: "Financial Services" },
  { symbol: "IRCTC", name: "Indian Railway Catering And Tourism Corp Ltd", scripCode: "542830", industry: "Consumer Services" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd", scripCode: "532187", industry: "Financial Services" },
  { symbol: "INDIGRID", name: "India Grid Trust", scripCode: "540565", industry: "Power" },
  { symbol: "IPCALAB", name: "IPCA Laboratories Ltd", scripCode: "524494", industry: "Healthcare" },
  { symbol: "JBCHEPHARM", name: "JB Chemicals & Pharmaceuticals Ltd", scripCode: "506943", industry: "Healthcare" },
  { symbol: "JKCEMENT", name: "JK Cement Ltd", scripCode: "532644", industry: "Construction Materials" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement Ltd", scripCode: "500380", industry: "Construction Materials" },
  { symbol: "JKPAPER", name: "JK Paper Ltd", scripCode: "532648", industry: "Forest Materials" },
  { symbol: "JMFINANCIL", name: "JM Financial Ltd", scripCode: "523405", industry: "Financial Services" },
  { symbol: "JSWENERGY", name: "JSW Energy Ltd", scripCode: "533148", industry: "Power" },
  { symbol: "JSWINFRA", name: "JSW Infrastructure Ltd", scripCode: "543994", industry: "Services" },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd", scripCode: "500228", industry: "Metals & Mining" },
  { symbol: "JINDALSAW", name: "Jindal Saw Ltd", scripCode: "500113", industry: "Capital Goods" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Ltd", scripCode: "532286", industry: "Metals & Mining" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks Ltd", scripCode: "533155", industry: "Consumer Services" },
  { symbol: "JUBLINGREA", name: "Jubilant Ingrevia Ltd", scripCode: "543271", industry: "Chemicals" },
  { symbol: "JUBLPHARMA", name: "Jubilant Pharmova Ltd", scripCode: "530019", industry: "Healthcare" },
  { symbol: "JUSTDIAL", name: "Just Dial Ltd", scripCode: "535648", industry: "Consumer Services" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs Ltd", scripCode: "532926", industry: "Fast Moving Consumer Goods" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India Ltd", scripCode: "543278", industry: "Consumer Durables" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints Ltd", scripCode: "500165", industry: "Consumer Durables" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank Ltd", scripCode: "590003", industry: "Financial Services" },
  { symbol: "KEI", name: "KEI Industries Ltd", scripCode: "517569", industry: "Capital Goods" },
  { symbol: "KEC", name: "KEC International Ltd", scripCode: "532714", industry: "Construction" },
  { symbol: "KFINTECH", name: "KFin Technologies Ltd", scripCode: "543720", industry: "Financial Services" },
  { symbol: "KPITTECH", name: "KPIT Technologies Ltd", scripCode: "542651", industry: "Information Technology" },
  { symbol: "KRBL", name: "KRBL Ltd", scripCode: "530813", industry: "Fast Moving Consumer Goods" },
  { symbol: "KSB", name: "KSB Ltd", scripCode: "500249", industry: "Capital Goods" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics Ltd", scripCode: "500233", industry: "Building Materials" },
  { symbol: "KALPATPOWR", name: "Kalpataru Projects International Ltd", scripCode: "522287", industry: "Construction" },
  { symbol: "KPRMILL", name: "K.P.R. Mill Ltd", scripCode: "532889", industry: "Textiles" },
  { symbol: "LAURUSLABS", name: "Laurus Labs Ltd", scripCode: "540222", industry: "Healthcare" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels Ltd", scripCode: "541233", industry: "Consumer Services" },
  { symbol: "LINDEINDIA", name: "Linde India Ltd", scripCode: "523457", industry: "Chemicals" },
  { symbol: "LUPIN", name: "Lupin Ltd", scripCode: "500257", industry: "Healthcare" },
  { symbol: "LUXIND", name: "Lux Industries Ltd", scripCode: "539542", industry: "Textiles" },
  { symbol: "MMTC", name: "MMTC Ltd", scripCode: "513377", industry: "Services" },
  { symbol: "MOIL", name: "MOIL Ltd", scripCode: "533286", industry: "Metals & Mining" },
  { symbol: "MRF", name: "MRF Ltd", scripCode: "500290", industry: "Automobile and Auto Components" },
  { symbol: "MGL", name: "Mahanagar Gas Ltd", scripCode: "539957", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace Developers Ltd", scripCode: "532313", industry: "Realty" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Ltd", scripCode: "531213", industry: "Financial Services" },
  { symbol: "MANKIND", name: "Mankind Pharma Ltd", scripCode: "543904", industry: "Healthcare" },
  { symbol: "MARICO", name: "Marico Ltd", scripCode: "531642", industry: "Fast Moving Consumer Goods" },
  { symbol: "MASTEK", name: "Mastek Ltd", scripCode: "523704", industry: "Information Technology" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute Ltd", scripCode: "543220", industry: "Healthcare" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders Ltd", scripCode: "543237", industry: "Capital Goods" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Ltd", scripCode: "542650", industry: "Healthcare" },
  { symbol: "MFSL", name: "Max Financial Services Ltd", scripCode: "500271", industry: "Financial Services" },
  { symbol: "MINDACORP", name: "Minda Corporation Ltd", scripCode: "538962", industry: "Automobile and Auto Components" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial Services Ltd", scripCode: "532892", industry: "Financial Services" },
  { symbol: "MPHASIS", name: "Mphasis Ltd", scripCode: "526299", industry: "Information Technology" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Ltd", scripCode: "533398", industry: "Financial Services" },
  { symbol: "NATCOPHARM", name: "Natco Pharma Ltd", scripCode: "524816", industry: "Healthcare" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International Ltd", scripCode: "532504", industry: "Chemicals" },
  { symbol: "NAUKRI", name: "Info Edge (India) Ltd", scripCode: "532777", industry: "Consumer Services" },
  { symbol: "NHPC", name: "NHPC Ltd", scripCode: "533098", industry: "Power" },
  { symbol: "NLCINDIA", name: "NLC India Ltd", scripCode: "513683", industry: "Power" },
  { symbol: "NMDC", name: "NMDC Ltd", scripCode: "526371", industry: "Metals & Mining" },
  { symbol: "NOCIL", name: "NOCIL Ltd", scripCode: "500730", industry: "Chemicals" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management Ltd", scripCode: "543988", industry: "Financial Services" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Ltd", scripCode: "533273", industry: "Realty" },
  { symbol: "OFSS", name: "Oracle Financial Services Software Ltd", scripCode: "532466", industry: "Information Technology" },
  { symbol: "OIL", name: "Oil India Ltd", scripCode: "533106", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "OLECTRA", name: "Olectra Greentech Ltd", scripCode: "532439", industry: "Automobile and Auto Components" },
  { symbol: "PAYTM", name: "One97 Communications Ltd (Paytm)", scripCode: "543396", industry: "Financial Services" },
  { symbol: "PAGEIND", name: "Page Industries Ltd", scripCode: "532827", industry: "Textiles" },
  { symbol: "PATANJALI", name: "Patanjali Foods Ltd", scripCode: "500368", industry: "Fast Moving Consumer Goods" },
  { symbol: "PERSISTENT", name: "Persistent Systems Ltd", scripCode: "533179", industry: "Information Technology" },
  { symbol: "PETRONET", name: "Petronet LNG Ltd", scripCode: "532522", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "PFIZER", name: "Pfizer Ltd", scripCode: "500680", industry: "Healthcare" },
  { symbol: "PHOENIXLTD", name: "The Phoenix Mills Ltd", scripCode: "503100", industry: "Realty" },
  { symbol: "PIIND", name: "PI Industries Ltd", scripCode: "523642", industry: "Chemicals" },
  { symbol: "POLICYBZR", name: "PB Fintech Ltd (PolicyBazaar)", scripCode: "543390", industry: "Financial Services" },
  { symbol: "POLYCAB", name: "Polycab India Ltd", scripCode: "542652", industry: "Capital Goods" },
  { symbol: "POONAWALLA", name: "Poonawalla Fincorp Ltd", scripCode: "524542", industry: "Financial Services" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects Ltd", scripCode: "533274", industry: "Realty" },
  { symbol: "PRINCEPIPE", name: "Prince Pipes and Fittings Ltd", scripCode: "542907", industry: "Building Materials" },
  { symbol: "PRSMJOHNSN", name: "Prism Johnson Ltd", scripCode: "500338", industry: "Construction Materials" },
  { symbol: "PVRINOX", name: "PVR INOX Ltd", scripCode: "532689", industry: "Media" },
  { symbol: "RBLBANK", name: "RBL Bank Ltd", scripCode: "540065", industry: "Financial Services" },
  { symbol: "REC", name: "REC Ltd", scripCode: "532955", industry: "Financial Services" },
  { symbol: "RADICO", name: "Radico Khaitan Ltd", scripCode: "532497", industry: "Fast Moving Consumer Goods" },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd", scripCode: "542649", industry: "Construction" },
  { symbol: "RAILTEL", name: "RailTel Corporation of India Ltd", scripCode: "543265", industry: "Telecommunication" },
  { symbol: "RAIN", name: "Rain Industries Ltd", scripCode: "500339", industry: "Chemicals" },
  { symbol: "RAJESHEXPO", name: "Rajesh Exports Ltd", scripCode: "531500", industry: "Consumer Durables" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements Ltd", scripCode: "500260", industry: "Construction Materials" },
  { symbol: "RITES", name: "RITES Ltd", scripCode: "541556", industry: "Construction" },
  { symbol: "ROUTE", name: "Route Mobile Ltd", scripCode: "543228", industry: "Telecommunication" },
  { symbol: "SBICARD", name: "SBI Cards and Payment Services Ltd", scripCode: "543066", industry: "Financial Services" },
  { symbol: "SHREECEM", name: "Shree Cement Ltd", scripCode: "500387", industry: "Construction Materials" },
  { symbol: "SRF", name: "SRF Ltd", scripCode: "503806", industry: "Chemicals" },
  { symbol: "SAIL", name: "Steel Authority of India Ltd", scripCode: "500113", industry: "Metals & Mining" },
  { symbol: "SJVN", name: "SJVN Ltd", scripCode: "533206", industry: "Power" },
  { symbol: "SKFINDIA", name: "SKF India Ltd", scripCode: "500472", industry: "Capital Goods" },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings Ltd", scripCode: "543300", industry: "Automobile and Auto Components" },
  { symbol: "STARHEALTH", name: "Star Health and Allied Insurance Company Ltd", scripCode: "543412", industry: "Financial Services" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance Ltd", scripCode: "590071", industry: "Financial Services" },
  { symbol: "SUNDRMFAST", name: "Sundram Fasteners Ltd", scripCode: "500403", industry: "Automobile and Auto Components" },
  { symbol: "SUNTV", name: "Sun TV Network Ltd", scripCode: "532733", industry: "Media" },
  { symbol: "SUPREMEIND", name: "Supreme Industries Ltd", scripCode: "509930", industry: "Building Materials" },
  { symbol: "SUZLON", name: "Suzlon Energy Ltd", scripCode: "532667", industry: "Capital Goods" },
  { symbol: "SYNGENE", name: "Syngene International Ltd", scripCode: "539268", industry: "Healthcare" },
  { symbol: "TATACHEM", name: "Tata Chemicals Ltd", scripCode: "500770", industry: "Chemicals" },
  { symbol: "TATACOMM", name: "Tata Communications Ltd", scripCode: "500483", industry: "Telecommunication" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd", scripCode: "500800", industry: "Fast Moving Consumer Goods" },
  { symbol: "TATAELXSI", name: "Tata Elxsi Ltd", scripCode: "500408", industry: "Information Technology" },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation Ltd", scripCode: "501301", industry: "Financial Services" },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd", scripCode: "500400", industry: "Power" },
  { symbol: "TATATECH", name: "Tata Technologies Ltd", scripCode: "544028", industry: "Information Technology" },
  { symbol: "TECHM", name: "Tech Mahindra Ltd", scripCode: "532755", industry: "Information Technology" },
  { symbol: "TEJASNET", name: "Tejas Networks Ltd", scripCode: "540595", industry: "Telecommunication" },
  { symbol: "THERMAX", name: "Thermax Ltd", scripCode: "500411", industry: "Capital Goods" },
  { symbol: "TIMKEN", name: "Timken India Ltd", scripCode: "522113", industry: "Capital Goods" },
  { symbol: "TORNTPOWER", name: "Torrent Power Ltd", scripCode: "532779", industry: "Power" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd", scripCode: "500420", industry: "Healthcare" },
  { symbol: "TRIDENT", name: "Trident Ltd", scripCode: "521064", industry: "Textiles" },
  { symbol: "TRITURBINE", name: "Triveni Turbine Ltd", scripCode: "533655", industry: "Capital Goods" },
  { symbol: "TIINDIA", name: "Tube Investments of India Ltd", scripCode: "540762", industry: "Automobile and Auto Components" },
  { symbol: "UCOBANK", name: "UCO Bank", scripCode: "532505", industry: "Financial Services" },
  { symbol: "UPL", name: "UPL Ltd", scripCode: "512070", industry: "Chemicals" },
  { symbol: "UTIAMC", name: "UTI Asset Management Company Ltd", scripCode: "543238", industry: "Financial Services" },
  { symbol: "VGUARD", name: "V-Guard Industries Ltd", scripCode: "532953", industry: "Consumer Durables" },
  { symbol: "VIPIND", name: "VIP Industries Ltd", scripCode: "507880", industry: "Consumer Durables" },
  { symbol: "VEDL", name: "Vedanta Ltd", scripCode: "500295", industry: "Metals & Mining" },
  { symbol: "VOLTAS", name: "Voltas Ltd", scripCode: "500575", industry: "Consumer Durables" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India Ltd", scripCode: "500238", industry: "Consumer Durables" },
  { symbol: "WIPRO", name: "Wipro Ltd", scripCode: "507685", industry: "Information Technology" },
  { symbol: "YESBANK", name: "Yes Bank Ltd", scripCode: "532648", industry: "Financial Services" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises Ltd", scripCode: "505537", industry: "Media" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies Ltd", scripCode: "504067", industry: "Information Technology" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Ltd", scripCode: "532321", industry: "Healthcare" },
  { symbol: "ZYDUSWELL", name: "Zydus Wellness Ltd", scripCode: "531335", industry: "Fast Moving Consumer Goods" },
  { symbol: "AARTIDRUGS", name: "Aarti Drugs Ltd", scripCode: "524348", industry: "Healthcare" },
  { symbol: "AARTIPHARM", name: "Aarti Pharmalabs Ltd", scripCode: "543709", industry: "Healthcare" },
  { symbol: "AFFLE", name: "Affle (India) Ltd", scripCode: "542752", industry: "Information Technology" },
  { symbol: "ALLCARGO", name: "Allcargo Logistics Ltd", scripCode: "532749", industry: "Services" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy & Mobility Ltd", scripCode: "500008", industry: "Automobile and Auto Components" },
  { symbol: "ANANTRAJ", name: "Anant Raj Ltd", scripCode: "515055", industry: "Realty" },
  { symbol: "APOLLOPIPE", name: "Apollo Pipes Ltd", scripCode: "531761", industry: "Building Materials" },
  { symbol: "ARVINDFASN", name: "Arvind Fashions Ltd", scripCode: "542484", industry: "Consumer Services" },
  { symbol: "ASAHISONG", name: "Asahi Songwon Colors Ltd", scripCode: "532853", industry: "Chemicals" },
  { symbol: "ASHOKA", name: "Ashoka Buildcon Ltd", scripCode: "532542", industry: "Construction" },
  { symbol: "ASTRAMICRO", name: "Astra Microwave Products Ltd", scripCode: "532493", industry: "Capital Goods" },
  { symbol: "ASTRAZEN", name: "AstraZeneca Pharma India Ltd", scripCode: "506820", industry: "Healthcare" },
  { symbol: "AUBANK", name: "AU Small Finance Bank Ltd", scripCode: "540611", industry: "Financial Services" },
  { symbol: "AVALON", name: "Avalon Technologies Ltd", scripCode: "543896", industry: "Capital Goods" },
  { symbol: "BALAMINES", name: "Balaji Amines Ltd", scripCode: "530999", industry: "Chemicals" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Ltd", scripCode: "502355", industry: "Automobile and Auto Components" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Ltd", scripCode: "500038", industry: "Fast Moving Consumer Goods" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd", scripCode: "541153", industry: "Financial Services" },
  { symbol: "BARBEQUE", name: "Barbeque-Nation Hospitality Ltd", scripCode: "543283", industry: "Consumer Services" },
  { symbol: "BBTC", name: "Bombay Burmah Trading Corporation Ltd", scripCode: "501425", industry: "Fast Moving Consumer Goods" },
  { symbol: "BECTORFOOD", name: "Mrs. Bectors Food Specialities Ltd", scripCode: "543253", industry: "Fast Moving Consumer Goods" },
  { symbol: "BOMDYEING", name: "Bombay Dyeing & Mfg Co Ltd", scripCode: "500020", industry: "Textiles" },
  { symbol: "BORORENEW", name: "Borosil Renewables Ltd", scripCode: "502219", industry: "Capital Goods" },
  { symbol: "BRIGADE", name: "Brigade Enterprises Ltd", scripCode: "532929", industry: "Realty" },
  { symbol: "BSE", name: "BSE Ltd", scripCode: "540362", industry: "Financial Services" },
  { symbol: "CAMPUS", name: "Campus Activewear Ltd", scripCode: "543523", industry: "Consumer Durables" },
  { symbol: "CANBK", name: "Canara Bank", scripCode: "532483", industry: "Financial Services" },
  { symbol: "CAPL", name: "Caplin Point Laboratories Ltd", scripCode: "524742", industry: "Healthcare" },
  { symbol: "CARERATING", name: "CARE Ratings Ltd", scripCode: "534804", industry: "Financial Services" },
  { symbol: "CCL", name: "CCL Products (India) Ltd", scripCode: "519600", industry: "Fast Moving Consumer Goods" },
  { symbol: "CESC", name: "CESC Ltd", scripCode: "500084", industry: "Power" },
  { symbol: "CHALET", name: "Chalet Hotels Ltd", scripCode: "542399", industry: "Consumer Services" },
  { symbol: "CIGNITITEC", name: "Cigniti Technologies Ltd", scripCode: "534758", industry: "Information Technology" },
  { symbol: "CRAFTSMAN", name: "Craftsman Automation Ltd", scripCode: "543276", industry: "Automobile and Auto Components" },
  { symbol: "CRISIL", name: "CRISIL Ltd", scripCode: "500092", industry: "Financial Services" },
  { symbol: "DCBBANK", name: "DCB Bank Ltd", scripCode: "532772", industry: "Financial Services" },
  { symbol: "DCMSHRIRAM", name: "DCM Shriram Ltd", scripCode: "523367", industry: "Chemicals" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilisers and Petrochemicals Corp Ltd", scripCode: "501425", industry: "Chemicals" },
  { symbol: "DELTACORP", name: "Delta Corp Ltd", scripCode: "532848", industry: "Consumer Services" },
  { symbol: "DHARMAJ", name: "Dharmaj Crop Guard Ltd", scripCode: "543685", industry: "Chemicals" },
  { symbol: "DHANI", name: "Dhani Services Ltd", scripCode: "532960", industry: "Financial Services" },
  { symbol: "DISHTV", name: "Dish TV India Ltd", scripCode: "532839", industry: "Media" },
  { symbol: "DODLA", name: "Dodla Dairy Ltd", scripCode: "543306", industry: "Fast Moving Consumer Goods" },
  { symbol: "EASEMYTRIP", name: "Easy Trip Planners Ltd", scripCode: "543272", industry: "Consumer Services" },
  { symbol: "EDELWEISS", name: "Edelweiss Financial Services Ltd", scripCode: "532922", industry: "Financial Services" },
  { symbol: "ENGINERSIN", name: "Engineers India Ltd", scripCode: "532178", industry: "Construction" },
  { symbol: "EPL", name: "EPL Ltd", scripCode: "500135", industry: "Industrial Manufacturing" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank Ltd", scripCode: "543243", industry: "Financial Services" },
  { symbol: "FIVESTAR", name: "Five-Star Business Finance Ltd", scripCode: "543663", industry: "Financial Services" },
  { symbol: "GABRIEL", name: "Gabriel India Ltd", scripCode: "505714", industry: "Automobile and Auto Components" },
  { symbol: "GARFIBRES", name: "Garware Technical Fibres Ltd", scripCode: "509557", industry: "Textiles" },
  { symbol: "GATEWAY", name: "Gateway Distriparks Ltd", scripCode: "543489", industry: "Services" },
  { symbol: "GICRE", name: "General Insurance Corporation of India", scripCode: "540755", industry: "Financial Services" },
  { symbol: "GILLETTE", name: "Gillette India Ltd", scripCode: "507815", industry: "Fast Moving Consumer Goods" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharmaceuticals Ltd", scripCode: "500660", industry: "Healthcare" },
  { symbol: "GLOBAL", name: "Global Surfaces Ltd", scripCode: "543829", industry: "Building Materials" },
  { symbol: "GLS", name: "Glenmark Life Sciences Ltd", scripCode: "543322", industry: "Healthcare" },
  { symbol: "GMMPFAUDLR", name: "GMM Pfaudler Ltd", scripCode: "505255", industry: "Capital Goods" },
  { symbol: "GMDCLTD", name: "Gujarat Mineral Development Corporation Ltd", scripCode: "532181", industry: "Metals & Mining" },
  { symbol: "GPIL", name: "Godawari Power and Ispat Ltd", scripCode: "532734", industry: "Metals & Mining" },
  { symbol: "GRAVITA", name: "Gravita India Ltd", scripCode: "533282", industry: "Metals & Mining" },
  { symbol: "GREENLAM", name: "Greenlam Industries Ltd", scripCode: "538979", industry: "Building Materials" },
  { symbol: "GREENPANEL", name: "Greenpanel Industries Ltd", scripCode: "542857", industry: "Building Materials" },
  { symbol: "GREENPLY", name: "Greenply Industries Ltd", scripCode: "526797", industry: "Building Materials" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders & Engineers Ltd", scripCode: "542011", industry: "Capital Goods" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers & Chemicals Ltd", scripCode: "500690", industry: "Chemicals" },
  { symbol: "GULFOILLUB", name: "Gulf Oil Lubricants India Ltd", scripCode: "538567", industry: "Oil Gas & Consumable Fuels" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies Ltd", scripCode: "543227", industry: "Information Technology" },
  { symbol: "HBLPOWER", name: "HBL Power Systems Ltd", scripCode: "517271", industry: "Capital Goods" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management Company Ltd", scripCode: "541729", industry: "Financial Services" },
  { symbol: "HEMIPROP", name: "Hemisphere Properties India Ltd", scripCode: "543242", industry: "Realty" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper Ltd", scripCode: "513599", industry: "Metals & Mining" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance Co Ltd", scripCode: "540716", industry: "Financial Services" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance Co Ltd", scripCode: "540133", industry: "Financial Services" },
  { symbol: "ISEC", name: "ICICI Securities Ltd", scripCode: "541179", industry: "Financial Services" },
  { symbol: "IDBI", name: "IDBI Bank Ltd", scripCode: "500116", industry: "Financial Services" },
  { symbol: "INDHOTEL", name: "The Indian Hotels Company Ltd", scripCode: "500850", industry: "Consumer Services" },
  { symbol: "INTELLECT", name: "Intellect Design Arena Ltd", scripCode: "538835", industry: "Information Technology" },
  { symbol: "IONEXCHANG", name: "Ion Exchange (India) Ltd", scripCode: "500214", industry: "Capital Goods" },
  { symbol: "J&KBANK", name: "The Jammu & Kashmir Bank Ltd", scripCode: "532209", industry: "Financial Services" },
  { symbol: "JAIBALAJI", name: "Jai Balaji Industries Ltd", scripCode: "532976", industry: "Metals & Mining" },
  { symbol: "JINDWORLD", name: "Jindal Worldwide Ltd", scripCode: "531543", industry: "Textiles" },
  { symbol: "JSL", name: "Jindal Stainless Ltd", scripCode: "532508", industry: "Metals & Mining" },
  { symbol: "KNRCON", name: "KNR Constructions Ltd", scripCode: "532942", industry: "Construction" },
  { symbol: "KPIL", name: "Kalpataru Projects International Ltd", scripCode: "522287", industry: "Construction" },
  { symbol: "KAYNES", name: "Kaynes Technology India Ltd", scripCode: "543664", industry: "Capital Goods" },
  { symbol: "KIRLOSENG", name: "Kirloskar Oil Engines Ltd", scripCode: "533295", industry: "Capital Goods" },
  { symbol: "KIRLOSBROS", name: "Kirloskar Brothers Ltd", scripCode: "500241", industry: "Capital Goods" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics Ltd", scripCode: "543398", industry: "Information Technology" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Ltd", scripCode: "500253", industry: "Financial Services" },
  { symbol: "MAPMYINDIA", name: "CE Info Systems Ltd (MapmyIndia)", scripCode: "543425", industry: "Information Technology" },
  { symbol: "MEDPLUS", name: "Medplus Health Services Ltd", scripCode: "543427", industry: "Healthcare" },
  { symbol: "METROBRAND", name: "Metro Brands Ltd", scripCode: "543426", industry: "Consumer Durables" },
  { symbol: "MIDHANI", name: "Mishra Dhatu Nigam Ltd", scripCode: "541195", industry: "Capital Goods" },
  { symbol: "MTARTECH", name: "MTAR Technologies Ltd", scripCode: "543270", industry: "Capital Goods" },
  { symbol: "NAZARA", name: "Nazara Technologies Ltd", scripCode: "543280", industry: "Information Technology" },
  { symbol: "NBCC", name: "NBCC (India) Ltd", scripCode: "534309", industry: "Construction" },
  { symbol: "NCC", name: "NCC Ltd", scripCode: "500294", industry: "Construction" },
  { symbol: "NETWORK18", name: "Network18 Media & Investments Ltd", scripCode: "532798", industry: "Media" },
  { symbol: "NEWGEN", name: "Newgen Software Technologies Ltd", scripCode: "540900", industry: "Information Technology" },
  { symbol: "NIPPONLIFE", name: "Nippon Life India Asset Management Ltd", scripCode: "540767", industry: "Financial Services" },
  { symbol: "PARADEEP", name: "Paradeep Phosphates Ltd", scripCode: "543530", industry: "Chemicals" },
  { symbol: "PNBHOUSING", name: "PNB Housing Finance Ltd", scripCode: "540173", industry: "Financial Services" },
  { symbol: "POLYMED", name: "Poly Medicure Ltd", scripCode: "531882", industry: "Healthcare" },
  { symbol: "POONAWALLA", name: "Poonawalla Fincorp Ltd", scripCode: "524542", industry: "Financial Services" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India Ltd", scripCode: "543187", industry: "Capital Goods" },
  { symbol: "PRAKASH", name: "Prakash Industries Ltd", scripCode: "506022", industry: "Metals & Mining" },
  { symbol: "PREMIERENE", name: "Premier Energies Ltd", scripCode: "544238", industry: "Capital Goods" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects Ltd", scripCode: "533274", industry: "Realty" },
  { symbol: "PRINCEPIPE", name: "Prince Pipes and Fittings Ltd", scripCode: "542907", industry: "Building Materials" },
  { symbol: "QUESS", name: "Quess Corp Ltd", scripCode: "539978", industry: "Services" },
  { symbol: "RAINBOW", name: "Rainbow Childrens Medicare Ltd", scripCode: "543524", industry: "Healthcare" },
  { symbol: "RALLIS", name: "Rallis India Ltd", scripCode: "500355", industry: "Chemicals" },
  { symbol: "RATNAMANI", name: "Ratnamani Metals & Tubes Ltd", scripCode: "520111", industry: "Capital Goods" },
  { symbol: "RAYMOND", name: "Raymond Ltd", scripCode: "500330", industry: "Consumer Discretionary" },
  { symbol: "RCF", name: "Rashtriya Chemicals and Fertilizers Ltd", scripCode: "524230", industry: "Chemicals" },
  { symbol: "REDINGTON", name: "Redington Ltd", scripCode: "532805", industry: "Services" },
  { symbol: "RELAXO", name: "Relaxo Footwears Ltd", scripCode: "530517", industry: "Consumer Durables" },
  { symbol: "RENUKA", name: "Shree Renuka Sugars Ltd", scripCode: "532670", industry: "Fast Moving Consumer Goods" },
  { symbol: "RHIM", name: "RHI Magnesita India Ltd", scripCode: "533470", industry: "Industrial Manufacturing" },
  { symbol: "ROLEXRINGS", name: "Rolex Rings Ltd", scripCode: "543325", industry: "Automobile and Auto Components" },
  { symbol: "SAFARI", name: "Safari Industries (India) Ltd", scripCode: "523025", industry: "Consumer Durables" },
  { symbol: "SANOFI", name: "Sanofi India Ltd", scripCode: "500674", industry: "Healthcare" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods India Ltd", scripCode: "543397", industry: "Consumer Services" },
  { symbol: "SAREGAMA", name: "Saregama India Ltd", scripCode: "506166", industry: "Media" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India Ltd", scripCode: "505790", industry: "Automobile and Auto Components" },
  { symbol: "SCHNEIDER", name: "Schneider Electric Infrastructure Ltd", scripCode: "534139", industry: "Capital Goods" },
  { symbol: "SHOPERSTOP", name: "Shoppers Stop Ltd", scripCode: "532638", industry: "Consumer Services" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance Ltd", scripCode: "511218", industry: "Financial Services" },
  { symbol: "SOBHA", name: "Sobha Ltd", scripCode: "532784", industry: "Realty" },
  { symbol: "SOLARINDS", name: "Solar Industries India Ltd", scripCode: "532725", industry: "Chemicals" },
  { symbol: "SONATSOFTW", name: "Sonata Software Ltd", scripCode: "532221", industry: "Information Technology" },
  { symbol: "SOUTHBANK", name: "The South Indian Bank Ltd", scripCode: "532218", industry: "Financial Services" },
  { symbol: "SPANDANA", name: "Spandana Sphoorty Financial Ltd", scripCode: "542759", industry: "Financial Services" },
  { symbol: "STARCEMENT", name: "Star Cement Ltd", scripCode: "540575", industry: "Construction Materials" },
  { symbol: "SUBROS", name: "Subros Ltd", scripCode: "517168", industry: "Automobile and Auto Components" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India Ltd", scripCode: "542920", industry: "Chemicals" },
  { symbol: "SUNCLAY", name: "Sundaram Clayton Ltd", scripCode: "543959", industry: "Automobile and Auto Components" },
  { symbol: "SUVENPHAR", name: "Suven Pharmaceuticals Ltd", scripCode: "543064", industry: "Healthcare" },
  { symbol: "SWANENERGY", name: "Swan Energy Ltd", scripCode: "503310", industry: "Diversified" },
  { symbol: "SYMPHONY", name: "Symphony Ltd", scripCode: "517385", industry: "Consumer Durables" },
  { symbol: "TANLA", name: "Tanla Platforms Ltd", scripCode: "532790", industry: "Information Technology" },
  { symbol: "TATACHEM", name: "Tata Chemicals Ltd", scripCode: "500770", industry: "Chemicals" },
  { symbol: "TEGA", name: "Tega Industries Ltd", scripCode: "543413", industry: "Capital Goods" },
  { symbol: "TRACXN", name: "Tracxn Technologies Ltd", scripCode: "543638", industry: "Information Technology" },
  { symbol: "TRIVENI", name: "Triveni Engineering & Industries Ltd", scripCode: "532356", industry: "Fast Moving Consumer Goods" },
  { symbol: "TTML", name: "Tata Teleservices (Maharashtra) Ltd", scripCode: "532371", industry: "Telecommunication" },
  { symbol: "TV18BRDCST", name: "TV18 Broadcast Ltd", scripCode: "532800", industry: "Media" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd", scripCode: "532343", industry: "Automobile and Auto Components" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank Ltd", scripCode: "542904", industry: "Financial Services" },
  { symbol: "USHAMART", name: "Usha Martin Ltd", scripCode: "517146", industry: "Capital Goods" },
  { symbol: "VAIBHAVGBL", name: "Vaibhav Global Ltd", scripCode: "532156", industry: "Consumer Durables" },
  { symbol: "VTL", name: "Vardhman Textiles Ltd", scripCode: "502986", industry: "Textiles" },
  { symbol: "WELCORP", name: "Welspun Corp Ltd", scripCode: "532144", industry: "Capital Goods" },
  { symbol: "WELENT", name: "Welspun Enterprises Ltd", scripCode: "532553", industry: "Construction" },
  { symbol: "WELSPUNLIV", name: "Welspun Living Ltd", scripCode: "514162", industry: "Textiles" },
  { symbol: "WESTLIFE", name: "Westlife Foodworld Ltd", scripCode: "505533", industry: "Consumer Services" },
  { symbol: "WOCKPHARMA", name: "Wockhardt Ltd", scripCode: "532300", industry: "Healthcare" },
  { symbol: "ZENTEC", name: "Zen Technologies Ltd", scripCode: "533339", industry: "Capital Goods" }
];

for (const s of additionalNifty500) {
  if (!masterMap.has(s.symbol)) {
    masterMap.set(s.symbol, s);
  }
}

const finalList = Array.from(masterMap.values());
console.log(`Compiled comprehensive Nifty 500 list with ${finalList.length} companies.`);

// Save to server/data/nifty500.json
const serverDataDir = path.resolve(__dirname, '../server/data');
if (!fs.existsSync(serverDataDir)) {
  fs.mkdirSync(serverDataDir, { recursive: true });
}
fs.writeFileSync(path.join(serverDataDir, 'nifty500.json'), JSON.stringify(finalList, null, 2), 'utf8');

// Save to data/nifty500.json
const dataDir = path.resolve(__dirname, '../data');
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}
fs.writeFileSync(path.join(dataDir, 'nifty500.json'), JSON.stringify(finalList, null, 2), 'utf8');

console.log('Successfully written nifty500.json to server/data/ and data/ directories!');
